global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: collector-otel
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
        - "collector:8888"
  - job_name: apps
    scrape_interval: 10s
    static_configs:
      - targets:
        - "collector:8889"